### ISSUE TITLE
No variants found for ':app'. Check build files to ensure at least one variant exists.报错

### ISSUE THREAD

**Issue by YuZhen-Yang** [yaoyi30/MobileUnet_ncnn_Android#2]

**Comment by yaoyi30** [comment]
你查查你的环境问题吧，这个代码是没有问题的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月2日(周二) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yaoyi30/MobileUnet_ncnn_Android_human_segmentation] No variants found for ':app'. Check build files to ensure at least one variant exists.报错 (Issue #2)

**Comment by YuZhen-Yang** [comment]
的确是我环境问题，切换为jdk  8 后，完美运行
